# Generated by Django 4.1.2 on 2022-11-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebFinal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellida',
            new_name='apellido',
        ),
    ]
