# Generated by Django 4.1.2 on 2022-11-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebFinal', '0002_rename_apellida_empleado_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
