# Generated by Django 4.1.2 on 2022-11-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebFinal', '0003_cliente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='legajo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
