# Generated by Django 4.1.2 on 2022-11-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebFinal', '0004_empleado_legajo_productos_codigo_proveedores_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='legajo',
            field=models.IntegerField(max_length=10),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('detalle', models.TextField(max_length=254)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebFinal.cliente')),
                ('venta', models.ManyToManyField(to='WebFinal.productos')),
            ],
        ),
    ]
