# Generated by Django 4.1.3 on 2022-12-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebFinal', '0008_productos_imagen_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, default='images/sin_imagen.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='detalle',
            field=models.TextField(max_length=254, verbose_name='Ingrese el detalle de la venta:'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='venta',
            field=models.ManyToManyField(to='WebFinal.productos', verbose_name='Seleccione Productos a vender:'),
        ),
    ]
